[package]
name = "bmw_deps"
version = "0.0.3-beta.1"
authors = ["BMW Develoeprs"]
description = "Dependencies of this library"
license = "Apache-2.0"
repository = "https://github.com/37miners/bmw"
keywords = [ "crypto", "bitcoinmw"]
readme = "README.md"
exclude = ["**/*.bmw", "**/*.bmw"]
edition = "2021"

[dependencies]
futures = "0.3.23"
failure = "0.1.0"
failure_derive = "0.1.0"
substring = "1.4.5"
openssl = "0.10.45"
pem = "1.1.0"
path-clean = "0.1.0"
rcgen = "0.10.0"
aes = { version = "0.7.0", features = ["ctr"] }
colored = "2.0.0"
x509-signature = "0.5.0"
zeroize = "1"
subtle = "2"
x25519-dalek = "1.2.0"
ed25519-dalek = "1.0.1"
rand = "0.8.4"
lazy_static = "1.4.0"
old_rand_core = { package = "rand_core", version = "0.5.1" }
rand_core = "0.6.4"
arrayref = "0.3.6"
backtrace = "0.3.63"
generic-array = "0.14.3"
chrono = "0.4"
dyn-clone = "1.0.9"
try-traits = "0.1.1"
sha3 = "0.10.0"
num-format = "0.4.0"
random-string = "1.0.0"
interprocess = "1.1.1"
libc = "0.2.132"
errno = "0.2.8"
portpicker = "0.1.1"
winapi = { version = "0.3.9", features = ["winsock2"] }
nix = "0.22.0"
bitvec = "1.0.1"
rustls = { version = "0.20.7", features = [ "dangerous_configuration" ]}
rustls-pemfile = "1.0.1"
webpki-roots = "0.22.4"
digest = "0.10.0"
typenum = "1.12"
cipher = "0.3.0"

[target.'cfg(target_os = "macos")'.dependencies]
kqueue-sys = "1.0.2"

[target.'cfg(target_os = "windows")'.dependencies]
wepoll-sys = "3.0.1"
